[tool.poetry]
name = "repaircars"
version = "0.1.0"
description = ""
authors = ["Kudryashov Alexander <kudryashoff568@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
