"""initial

Revision ID: de90de049862
Revises: 
Create Date: 2024-11-01 08:16:19.723745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de90de049862'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS my_app_schema')
    op.create_table('clients_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('phone_number', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('total_amount_of_work', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='my_app_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients_list', schema='my_app_schema')
    # ### end Alembic commands ###
